### ISSUE TITLE
Error connecting to server: https://itunes.apple.com

### ISSUE THREAD

**Issue by horacecar** [jonaaa20/itunes-web-sources#10]
Error connecting to server: https://itunes.apple.com

>>provided uri is invalid:
https://itunes.apple.com/lookup?country=US&entity=song&limit=200&id="1377782435"&entity=song&limit=200

last week is fine, but since yesterday, that error occur. please help to fix.HAHAHAHHA

**Comment by horacecar** [comment]
![image](https://user-images.githubusercontent.com/44496483/47560444-ca525200-d94a-11e8-9a5a-feaf8f097e8f.png)

**Comment by jonaaa20** [comment]
Can you please check the releases?
