### ISSUE TITLE
iTunes Web Sources for MP3Tag 

### ISSUE THREAD

**Issue by WelbertySoares** [jonaaa20/itunes-web-sources#11]
I wanted to inform you that all iTunes Web Sources stopped working, you can create new ones, I can not use these, please.

**Comment by WelbertySoares** [comment]
check out

![erro](https://user-images.githubusercontent.com/44514656/47598168-7ce7dc00-d96e-11e8-8dd9-fd6f2d84c1af.png)

**Comment by jonaaa20** [comment]
Can you PLEASE check the releases? i've posted a new version yesterday and it's working fine on my end.

**Comment by WelbertySoares** [comment]
Yesterday was working normally I downloaded this, and it is not working here, the error still persists.

**Comment by WelbertySoares** [comment]
I added a new song, recently released and it was not.

![image](https://user-images.githubusercontent.com/44514656/47598225-50808f80-d96f-11e8-97e0-9f4cac46754e.png)

**Comment by jonaaa20** [comment]
Check the recent release, the problem have been already fixed.

Locking the issue.
