### ISSUE TITLE
search results error

### ISSUE THREAD

**Issue by rezow** [jonaaa20/itunes-web-sources#12]
When searching for an album, the following is returned - "Sorry, no entries are matching your search criteria." This issue just started today, as I've been using these sources every day this week and they've worked fine and returned results..

**Comment by jonaaa20** [comment]
Use the old 0.3.1.

https://github.com/jonaaa20/itunes-web-sources/releases/tag/v0.3.1

**Comment by rezow** [comment]
It now works as it should. Thanks for the fast response.
