### ISSUE TITLE
Error in instructions!

### ISSUE THREAD

**Issue by TheRealMoleman** [jonaaa20/itunes-web-sources#13]
FYI, the instructions state to copy the files to %appdata%\**roaming\**mp3tag\data which is incorrect, as %appdata% automatically expands to <drive>:\users\<username>\AppData\ so stating the extra \roaming\ results in an invalid path.

(In others words, something like c:\Users\hfelsh\roaming\roaming\mp3tag\data, which is incorrect as it states a roaming subfolder to the roaming folder. Hope that makes sense.)

Users only have to copy the files to the folders:

%appdata%\mp3tag\data\actions
%appdata%\mp3tag\data\sources

You may wish to update the instructions accordingly.

**Comment by jonaaa20** [comment]
Fixed.
