### ISSUE TITLE
Error iTunes Source Mp3Tag [v0.3.1]

### ISSUE THREAD

**Issue by WelbertySoares** [jonaaa20/itunes-web-sources#15]
Has it returned an error again, does it have a new update or not

![image](https://user-images.githubusercontent.com/44514656/48648898-0e7bc400-e9d8-11e8-852b-e6de24b6465d.png)

#11 

@jonaaa20

**Comment by jonaaa20** [comment]
![mp3tag_iolhmpvwbc](https://user-images.githubusercontent.com/19306370/48650271-a5e31600-e9dc-11e8-9131-9e31e2ca6b2f.png)

0.3.1, working fine.

**Comment by shillshocked** [comment]
Which version of Mp3Tag is compatible? Because I haven't seen anyone using 2.90f with it yet.

**Comment by jonaaa20** [comment]
Like I've said, also working fine on the **latest** version (2.91).

**Comment by simonesolazzo** [comment]
I have the same problem. I'm trying with iTunes#Italia.src (0.3.2) and iTunes#United States of America.src (0.3.2) but they don't work with me. I have the latest version of Mp3Tag (2.91)

**Comment by jonaaa20** [comment]
@simonesolazzo please check the releases, instead of reporting here, create a individual issue.

Besides, everything's working fine.

Italia source used.

![mp3tag_3pu2c7ro0d](https://user-images.githubusercontent.com/19306370/49832954-47148080-fd7f-11e8-98e5-b603a058b1b6.png)
