### ISSUE TITLE
[Suggestion] How about multiple genres?

### ISSUE THREAD

**Issue by shillshocked** [jonaaa20/itunes-web-sources#16]
Rather than just the primary genre tag.

**Comment by jonaaa20** [comment]
The script will only add the genre present on the iTunes API, if there's only one genre on the API, it will only add one genre.

**Comment by jonaaa20** [comment]
No plans for adding multiple genres for now, I will consider this in a future release.

**Comment by shillshocked** [comment]
It would be nice to get the subgenres, too.

**Comment by jonaaa20** [comment]
I will close this issue for now, probably i will reopen, don't know, i tried to implement multiple genres but the API doesn't seem to support it.
