### ISSUE TITLE
This script doesn't work with the latest version of Mp3Tag (2.90f)

### ISSUE THREAD

**Issue by shillshocked** [jonaaa20/itunes-web-sources#17]
I tried using the United States script and I consistently get no results, older script from another source works fine.

**Comment by jonaaa20** [comment]
Duplicate of #15, v0.3.1 is working fine.
![mp3tag_0velmyttws](https://user-images.githubusercontent.com/19306370/49271891-aeb0fe80-f456-11e8-8907-ed8134664d7d.png)

**Comment by shillshocked** [comment]
Did you try on the latest version, 2.9.0f?
