### ISSUE TITLE
[Discussion] Take trackNumber from lookup?

### ISSUE THREAD

**Issue by FLX90** [jonaaa20/itunes-web-sources#18]
Hey,

I have one question.

Why you don't pull the trackNumber from the Lookup?

Best regards,
Felix

**Comment by jonaaa20** [comment]
trackNumber is useful for .m4a songs.

**Comment by FLX90** [comment]
Okay, I only have m4a-files.
mp3 don't uses trackNumber?

**Comment by jonaaa20** [comment]
I don't know, I generally use m4a instead of mp3.

**Comment by FLX90** [comment]
Me too.
So i added the trackNumber to source.
