### ISSUE TITLE
Wrong track and date renaming

### ISSUE THREAD

**Issue by Mrakobes666** [jonaaa20/itunes-web-sources#21]
when renaming an individual track, the script takes the first name in the album and renames for example the eighth track with the name of the first. I would like to insert the date of release and not that there is substituted, the release date of original album

**Comment by jonaaa20** [comment]
Sorry but I can't understand the problem here, about the renaming, this isn't related to the script, but with mp3tag.

I will leave this opened because I  didn't understand your problem.

**Comment by Mrakobes666** [comment]
mp3tag, when you insert a cover in the file, I recognize the track on itunes, the track is determined, but in the album it is not the first, after inserting the cover the original file changes the tags to the first in the found album, also changes the release date to the wrong real

**Comment by jonaaa20** [comment]
This isn't related to the script, what you're saying is related to mp3tag itself.

You must select all the files to change the cover art. 

About the release date, if the release date is wrong, it's iTunes fault.

**Comment by jonaaa20** [comment]
Due to the lack of response of the issue author, i'm closing the issue for now.
