### ISSUE TITLE
Problem with the composers?

### ISSUE THREAD

**Issue by JBey4you** [jonaaa20/itunes-web-sources#8]
Hello,

iTunes Web Sources is truly perfect, I was looking for this kind of tool for several years now. Although, I think there is a problem with the composers (maybe Apple changed something on its side), because every single time the composer = the name of the artists. I am using the France version, but the problem also appears with the U.S. version.

Any idea maybe?

Thanks!

**Comment by jonaaa20** [comment]
**Composers uses the same name as artist field** 

Because iTunes API doesn't provide composer information.
